services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-runtime
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION_STRING}
    container_name: backend
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-nginx
    ports:
      - "80:80"
    environment:
      - VITE_MAPBOX_ACCESS_KEY=${VITE_MAPBOX_ACCESS_KEY}
    container_name: frontend
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=navio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: