services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-runtime
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    container_name: backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-runtime
    ports:
      - "5173:5173"
    container_name: frontend
    depends_on:
      - backend