apiVersion: v1
kind: Service
metadata:
  name: navio-backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: navio-backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: navio-backend
spec:
  selector:
    matchLabels:
      app: navio-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: navio-backend
    spec:
      containers:
        - image: navio-backend-image
          name: navio-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY

---

apiVersion: v1
kind: Service
metadata:
  name: navio-frontend
spec:
  ports:
    - port: 5173
      targetPort: 5173
  selector:
    app: navio-frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: navio-frontend
spec:
  selector:
    matchLabels:
      app: navio-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: navio-frontend
    spec:
      containers:
        - image: navio-frontend-image
          name: navio-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          env:
            - name: VITE_MAPBOX_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: VITE_MAPBOX_ACCESS_KEY