apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
namespace: navio-staging
resources:
  - namespace.yaml
images:
  - name: navio-backend-image
  - name: navio-frontend-image
