name: CI/CD

on:
  push:
    branches: [ "main", "dev", "fix" ]
  pull_request:
    branches: [ "main", "dev", "fix" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist/

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: ./mvnw clean install

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar

  build-docker-images:
    runs-on: ubuntu-latest
    needs: [ build-frontend, build-backend ]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/fix')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          target: backend-runtime
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/navio-backend:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/navio-backend:${{ github.ref_name }}-${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/navio-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          target: frontend-nginx
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/navio-frontend:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/navio-frontend:${{ github.ref_name }}-${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/navio-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output deployment commands
        run: |
          echo "🚀 Docker images built successfully!"
          echo ""
          echo "📦 Built images:"
          echo "  - ghcr.io/${{ github.repository_owner }}/navio-backend:${{ github.ref_name }}"
          echo "  - ghcr.io/${{ github.repository_owner }}/navio-frontend:${{ github.ref_name }}"
          echo ""
          echo "🛠️ To deploy locally, run these commands:"
          echo ""
          echo "# 1. Pull the new images"
          echo "docker pull ghcr.io/${{ github.repository_owner }}/navio-backend:${{ github.ref_name }}"
          echo "docker pull ghcr.io/${{ github.repository_owner }}/navio-frontend:${{ github.ref_name }}"
          echo ""
          echo "# 2. Update your deployment.yaml image tags and apply"
          echo "kubectl apply -f kubernetes/namespace.yaml"
          echo "kubectl create configmap app-config --from-env-file=.env -n navio-dev"
          echo "kubectl apply -f kubernetes/deployment.yaml"
          echo ""
          echo "# 3. Or use the quick update script (if available)"
          echo "./scripts/deploy.sh ${{ github.ref_name }}"
